=== mborysenko/laboratory/projects/catalogue/Common/Library/Core/configuration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="Schemas/applicationHost.xsd"/>
	<xs:include schemaLocation="Schemas/manifest.xsd"/>
	<xs:include schemaLocation="Schemas/hosting.xsd"/>
	
	<xs:element name="configuration" type="typeConfiguration" />

	<xs:complexType name="typeConfiguration">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:choice>
				<xs:element type="typeAppSettings" name="appSettings" minOccurs="0" maxOccurs="1" />
				<xs:element type="typePages" name="pages" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeInclude" name="include" minOccurs="0" maxOccurs="unbounded" />
				<xs:element type="typeResourceGroups" name="resourceGroups" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeExtensions" name="extensions" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeCustomSections" name="customSections" minOccurs="0" maxOccurs="1" />
				<xs:element type="typePackages" name="packages" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeApplicationHost" name="applicationHost" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeApplicationSuite" name="applicationSuite" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeHosting" name="hosting" minOccurs="0" maxOccurs="1" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="merge" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="generated" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	
	<xs:complexType name="typeAppSettings">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="setting" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typePages">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="page" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="preloadPackages" minOccurs="0">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="package" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="optional" />
											<xs:attribute name="url" type="xs:string" use="required" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="url" type="xs:string" use="required" />
					<xs:attribute name="view" type="xs:string" use="optional" />
					<xs:attribute name="resource" type="xs:string" use="optional" />
					<xs:attribute name="title" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="baseUrl" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="typeResourceGroups">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="resourceGroup">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="files" minOccurs="0">
							<xs:complexType>
								<xs:sequence minOccurs="0">
									<xs:element minOccurs="0" maxOccurs="unbounded" name="file">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required" />
											<xs:attribute name="modification" type="xs:string" use="optional" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" name="dependencies">
							<xs:complexType>
								<xs:sequence minOccurs="0">
									<xs:element maxOccurs="unbounded" name="dependency">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="packaging" type="typeGroupPackaging" use="optional" default="auto"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeInclude">
		<xs:sequence>
			<xs:element name="configuration" type="typeConfiguration" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="src" type="xs:string" use="required" />
		<xs:attribute name="modification" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="typeExtensions">
		<xs:sequence>
			<xs:element name="resourceExtension" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="insert" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="position" type="typeInsertPosition"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="for" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeCustomSections">
		<xs:sequence minOccurs="0">
			<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typePackages">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="package">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="resourceGroups" type="typeResourceGroups" />
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="recursive" type="typePackageRecursive" use="optional" default="auto"/>
					<xs:attribute name="src" type="xs:string" use="optional"/>
					<xs:attribute name="modification" type="xs:string" use="optional" />
					<xs:attribute name="location" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="typeInsertPosition">
		<xs:restriction base="xs:string">
			<xs:enumeration value="before"/>
			<xs:enumeration value="after"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="typeGroupPackaging">
		<xs:restriction base="xs:string">
			<xs:enumeration value="auto"/>
			<xs:enumeration value="exclude"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="typePackageRecursive">
		<xs:annotation>
			<xs:documentation>
				Defines whether dependencies of the specified resource groups should be included too:
				'false' means the dependencies should not be included;
				'auto' (default) means the dependencies should be included, unless another package has them included;
				'true' forces all dependedncies to be included. Use with causion: may result in resources included in multiple groups.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="auto"/>
			<xs:enumeration value="false"/>
			<xs:enumeration value="true"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== mborysenko/laboratory/projects/catalogue/Common/Library/UI/Views/Resources/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../SDL.Client.Core/configuration.xsd">

	<resourceGroups>
		<resourceGroup name="SDL.UI.Views.Resources">
			<files>
				<file name="resources.default.resjson"/>
				<file name="resources.{CULTURE}.resjson"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Libraries.SDL.Globalize"/>
			</dependencies>
		</resourceGroup>
	</resourceGroups>

</configuration>

=== mborysenko/laboratory/projects/architecture/Library/Core/Types/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../configuration.xsd">
	<resourceGroups>

		<resourceGroup name="SDL.Client.Types">
			<dependencies>
				<dependency name="SDL.Client.Types.DisposableObject"/>
				<dependency name="SDL.Client.Types.ObjectWithEvents"/>
				<dependency name="SDL.Client.Types.OO"/>
				<dependency name="SDL.Client.Types.Url"/>
				<dependency name="SDL.Client.Types.String"/>
				<dependency name="SDL.Client.Types.Array"/>
				<dependency name="SDL.Client.Types.Date"/>
				<dependency name="SDL.Client.Types.RegExp"/>
				<dependency name="SDL.Client.Types.Function"/>
				<dependency name="SDL.Client.Types.Object"/>
				<dependency name="SDL.Client.Types.Number"/>
			</dependencies>
		</resourceGroup>
		
		<resourceGroup name="SDL.Client.Types.DisposableObject">
			<files>
				<file name="DisposableObject.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.OO"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.ObjectWithEvents">
			<files>
				<file name="ObjectWithEvents.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.DisposableObject"/>
				<dependency name="SDL.Client.Types.Object"/>
				<dependency name="SDL.Client.Event.Event"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.OO">
			<files>
				<file name="OO.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Diagnostics"/>
				<dependency name="SDL.Client.Types.Base"/>
				<dependency name="SDL.Client.Types.Array"/>
				<dependency name="SDL.Client.Types.Function"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.Base">
			<files>
				<file name="Types.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Libraries.SDL.JQuery"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.Url">
			<files>
				<file name="Url.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Diagnostics"/>
				<dependency name="SDL.Client.Types.Base"/>
				<dependency name="SDL.Client.Types.RegExp"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.String">
			<files>
				<file name="String.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.Base"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.Array">
			<files>
				<file name="Array.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.Base"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.Date">
			<files>
				<file name="Date.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.Base"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.RegExp">
			<files>
				<file name="RegExp.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.Base"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.Function">
			<files>
				<file name="Function.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.Base"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.Object">
			<files>
				<file name="Object.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.Base"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Types.Number">
			<files>
				<file name="Number.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.Base"/>
			</dependencies>
		</resourceGroup>

	</resourceGroups>
</configuration>

=== mborysenko/laboratory/projects/architecture/Library/UI/Core/Renderers/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../SDL.Client.Core/configuration.xsd">
	<resourceGroups>
		
		<resourceGroup name="SDL.UI.Core.Renderers">
			<dependencies>
				<dependency name="SDL.UI.Core.Renderers.ControlRenderer"/>
				<dependency name="SDL.UI.Core.Renderers.ViewRenderer"/>
			</dependencies>
		</resourceGroup>
		
		<resourceGroup name="SDL.UI.Core.Renderers.ControlRenderer">
			<files>
				<file name="ControlRenderer.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Diagnostics"/>
				<dependency name="SDL.Client.Types.Base"/>
				<dependency name="SDL.Client.Types.Array"/>
			</dependencies>
		</resourceGroup>
		
		<resourceGroup name="SDL.UI.Core.Renderers.ViewRenderer">
			<files>
				<file name="ViewRenderer.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Diagnostics"/>
				<dependency name="SDL.Client.Types.Base"/>
				<dependency name="SDL.Client.Types.Array"/>
			</dependencies>
		</resourceGroup>

	</resourceGroups>

</configuration>

=== mborysenko/laboratory/projects/architecture/Library/UI/Controls.Knockout/configuration.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../SDL.Client.Core/configuration.xsd" generated="true">
  <appSettings>
    <setting name="version" value="1.0.0.288" />
  </appSettings>
  <!-- SDL.UI.Controls configuration -->
  <include src="../Controls/configuration.xml" />
  <!-- SDL.UI.Core.Knockout configuration -->
  <include src="../Core.Knockout/configuration.xml" />
  <!-- Controls -->
  <include src="Tooltip/_Config.xml">
    <configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <resourceGroups>
        <resourceGroup name="SDL.UI.Controls.Knockout.Tooltip">
          <files>
            <file name="Tooltip/Tooltip.js" />
          </files>
          <dependencies>
            <dependency name="SDL.UI.Core.Knockout.Controls" />
            <dependency name="SDL.UI.Controls.Tooltip" />
          </dependencies>
        </resourceGroup>
      </resourceGroups>
    </configuration>
  </include>
  <!-- Packages -->
  <include src="packages.xml">
    <configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <packages>
        <package name="SDL.UI.Controls.Knockout" src="Packages/SDL.UI.Controls.Knockout.js">
          <resourceGroups>
            <resourceGroup name="SDL.UI.Controls.Knockout.Tooltip" />
          </resourceGroups>
        </package>
      </packages>
    </configuration>
  </include>
  <resourceGroups></resourceGroups>
  <packages />
</configuration>

=== mborysenko/laboratory/projects/architecture/Library/Core/Models/MessageCenter/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../configuration.xsd">

	<resourceGroups>
		<resourceGroup name="SDL.Client.Models.MessageCenter">
			<files>
				<file name="MessageCenter.js"/>
				<file name="Message.js"/>
				<file name="NotificationMessage.js"/>
				<file name="WarningMessage.js"/>
				<file name="ErrorMessage.js"/>
				<file name="QuestionMessage.js"/>
				<file name="GoalMessage.js"/>
				<file name="ProgressMessage.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models"/>
				<dependency name="SDL.Client.MessageCenter"/>
			</dependencies>
		</resourceGroup>
	</resourceGroups>

</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/ApplicationHost/ApplicationHost/Views/Frame/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			   xsi:noNamespaceSchemaLocation="..\..\..\..\..\SDL.Client\SDL.Client.Core\configuration.xsd">

	<resourceGroups>
		<resourceGroup name="SDL.Client.UI.ApplicationHost.Views.Frame">
			<files>
				<file name="Frame.js"/>
				<file name="styles/Frame.css"/>
				<file name="cultures/frame.js"/>
				<file name="cultures/frame.{CULTURE}.js"/>
				<file name="Frame.htm"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.UI.ApplicationHost.ViewModels"/>
				<dependency name="SDL.UI.Core.Views.ViewBase"/>
				<dependency name="SDL.UI.Core.Knockout.Renderers"/>
				<dependency name="SDL.UI.Core.Knockout.BindingHandlers"/>
				<dependency name="SDL.Client.Libraries.SDL.Globalize"/>
				<dependency name="SDL.UI.Controls.Knockout.TopBar"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.UI.ApplicationHost.Views.Frame.Init">
			<dependencies>
				<dependency name="SDL.Client.UI.ApplicationHost.Views.Frame"/>
				<dependency name="SDL.UI.Core.Init"/>
			</dependencies>
		</resourceGroup>
		
	</resourceGroups>

</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/UI/Controls/packages.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../SDL.Client.Core/configuration.xsd">

	<packages>
		<package name="SDL.UI.Controls">
			<resourceGroups>
				<resourceGroup name="SDL.UI.Controls.Button"/>
				<resourceGroup name="SDL.UI.Controls.Callout"/>
				<resourceGroup name="SDL.UI.Controls.Dialog"/>
				<resourceGroup name="SDL.UI.Controls.Message"/>
				<resourceGroup name="SDL.UI.Controls.Tabs"/>
				<resourceGroup name="SDL.UI.Controls.Tooltip"/>
				<resourceGroup name="SDL.UI.Controls.ScrollView"/>
			</resourceGroups>
		</package>

		<package name="SDL.UI.Controls.JQuery">
			<resourceGroups>
				<resourceGroup name="SDL.UI.Controls.JQuery.Button"/>
				<resourceGroup name="SDL.UI.Controls.JQuery.Callout"/>
				<resourceGroup name="SDL.UI.Controls.JQuery.Dialog"/>
				<resourceGroup name="SDL.UI.Controls.JQuery.Message"/>
				<resourceGroup name="SDL.UI.Controls.JQuery.Tabs"/>
				<resourceGroup name="SDL.UI.Controls.JQuery.Tooltip"/>
				<resourceGroup name="SDL.UI.Controls.JQuery.ScrollView"/>
			</resourceGroups>
		</package>
	</packages>

</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/UI/Controls/LibraryPanel/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../SDL.Client.Core/configuration.xsd">

    <resourceGroups>
        <resourceGroup name="SDL.UI.Controls.LibraryPanel">
            <files>
                <file name="Styles\sdl.carbon2.library-panel.css"/>
                <file name="SDL.UI.Controls.LibraryPanel.js"/>
                <file name="Resource\resources.js"/>
            </files>
            <dependencies>
                <dependency name="SDL.UI.Core.Controls.ControlBase"/>
                <dependency name="SDL.UI.Controls.ScrollView"/>
                <dependency name="SDL.UI.Controls.Button"/>
                <dependency name="SDL.Client.UI.Core.Libraries.Polyfills"/>
            </dependencies>
        </resourceGroup>

        <resourceGroup name="SDL.UI.Controls.JQuery.LibraryPanel">
            <files>
                <file name="SDL.UI.Controls.LibraryPanel.jQuery.js"/>
            </files>
            <dependencies>
                <dependency name="SDL.Client.Libraries.SDL.JQuery"/>
                <dependency name="SDL.UI.Core.Controls.JQuery"/>
                <dependency name="SDL.UI.Controls.LibraryPanel"/>
            </dependencies>
        </resourceGroup>
    </resourceGroups>

</configuration>
