=== mborysenko/laboratory/projects/catalogue/Common/Library/Core/configuration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="Schemas/applicationHost.xsd"/>
	<xs:include schemaLocation="Schemas/manifest.xsd"/>
	<xs:include schemaLocation="Schemas/hosting.xsd"/>
	
	<xs:element name="configuration" type="typeConfiguration" />

	<xs:complexType name="typeConfiguration">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:choice>
				<xs:element type="typeAppSettings" name="appSettings" minOccurs="0" maxOccurs="1" />
				<xs:element type="typePages" name="pages" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeInclude" name="include" minOccurs="0" maxOccurs="unbounded" />
				<xs:element type="typeResourceGroups" name="resourceGroups" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeExtensions" name="extensions" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeCustomSections" name="customSections" minOccurs="0" maxOccurs="1" />
				<xs:element type="typePackages" name="packages" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeApplicationHost" name="applicationHost" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeApplicationSuite" name="applicationSuite" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeHosting" name="hosting" minOccurs="0" maxOccurs="1" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="merge" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="generated" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	
	<xs:complexType name="typeAppSettings">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="setting" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typePages">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="page" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="preloadPackages" minOccurs="0">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="package" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="optional" />
											<xs:attribute name="url" type="xs:string" use="required" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="url" type="xs:string" use="required" />
					<xs:attribute name="view" type="xs:string" use="optional" />
					<xs:attribute name="resource" type="xs:string" use="optional" />
					<xs:attribute name="title" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="baseUrl" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="typeResourceGroups">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="resourceGroup">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="files" minOccurs="0">
							<xs:complexType>
								<xs:sequence minOccurs="0">
									<xs:element minOccurs="0" maxOccurs="unbounded" name="file">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required" />
											<xs:attribute name="modification" type="xs:string" use="optional" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" name="dependencies">
							<xs:complexType>
								<xs:sequence minOccurs="0">
									<xs:element maxOccurs="unbounded" name="dependency">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="packaging" type="typeGroupPackaging" use="optional" default="auto"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeInclude">
		<xs:sequence>
			<xs:element name="configuration" type="typeConfiguration" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="src" type="xs:string" use="required" />
		<xs:attribute name="modification" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="typeExtensions">
		<xs:sequence>
			<xs:element name="resourceExtension" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="insert" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="position" type="typeInsertPosition"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="for" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeCustomSections">
		<xs:sequence minOccurs="0">
			<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typePackages">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="package">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="resourceGroups" type="typeResourceGroups" />
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="recursive" type="typePackageRecursive" use="optional" default="auto"/>
					<xs:attribute name="src" type="xs:string" use="optional"/>
					<xs:attribute name="modification" type="xs:string" use="optional" />
					<xs:attribute name="location" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="typeInsertPosition">
		<xs:restriction base="xs:string">
			<xs:enumeration value="before"/>
			<xs:enumeration value="after"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="typeGroupPackaging">
		<xs:restriction base="xs:string">
			<xs:enumeration value="auto"/>
			<xs:enumeration value="exclude"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="typePackageRecursive">
		<xs:annotation>
			<xs:documentation>
				Defines whether dependencies of the specified resource groups should be included too:
				'false' means the dependencies should not be included;
				'auto' (default) means the dependencies should be included, unless another package has them included;
				'true' forces all dependedncies to be included. Use with causion: may result in resources included in multiple groups.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="auto"/>
			<xs:enumeration value="false"/>
			<xs:enumeration value="true"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== mborysenko/laboratory/projects/architecture/Library/UI/Core.Knockout/ViewModels/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../SDL.Client.Core/configuration.xsd">

	<resourceGroups>

		<resourceGroup name="SDL.UI.Core.Knockout.ViewModels">
			<files>
				<file name="ViewModelItem.js"/>
				<file name="ViewModel.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.OO"/>
				<dependency name="SDL.Client.Models"/>
				<dependency name="SDL.UI.Core.Knockout.ViewModels.Base"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.UI.Core.Knockout.ViewModels.Base">
			<files>
				<file name="ViewModelBase.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.UI.Core.Knockout.Libraries.Knockout"/>
				<dependency name="SDL.Client.Libraries.SDL.Globalize"/>
			</dependencies>
		</resourceGroup>
	
	</resourceGroups>
</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/Core/Libraries/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../configuration.xsd">

	<include src="jQuery/_Config.xml"/>
	<include src="Globalize/_Config.xml"/>

	<!-- All Libraries -->
	<resourceGroups>
		<resourceGroup name="SDL.Client.Libraries">
			<dependencies>
				<dependency name="SDL.Client.Libraries.SDL.JQuery"/>
				<dependency name="SDL.Client.Libraries.SDL.Globalize"/>
			</dependencies>
		</resourceGroup>
	</resourceGroups>

</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/UI/Controls/Button/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../SDL.Client.Core/configuration.xsd">

	<resourceGroups>
		<resourceGroup name="SDL.UI.Controls.Button">
			<files>
				<file name="Button.js"/>
				<file name="Button.css"/>
			</files>
			<dependencies>
				<dependency name="SDL.UI.Core.Controls.ControlBase"/>
				<dependency name="SDL.UI.Core.Event.Constants"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.UI.Controls.JQuery.Button">
			<files>
				<file name="Button.jQuery.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Libraries.SDL.JQuery"/>
				<dependency name="SDL.UI.Core.Controls.JQuery"/>
				<dependency name="SDL.UI.Controls.Button"/>
			</dependencies>
		</resourceGroup>
	</resourceGroups>

</configuration>

=== mborysenko/laboratory/projects/catalogue/Leviafan/ViewModelItems/_config.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../../Common/Library/Core/configuration.xsd">
    <resourceGroups>

        <resourceGroup name="LVF.ViewModelItems.Store">
            <files>
                <file name="Store.js" />
            </files>
            <dependencies>
                <dependency name="SDL.UI.Core.Knockout.ViewModels" />
                <dependency name="SDL.UI.Core.Knockout.ViewModels.Base" />
            </dependencies>
        </resourceGroup>

        <resourceGroup name="LVF.ViewModelItems.ProductList">
            <files>
                <file name="ProductList.js"/>
            </files>
            <dependencies>
                <dependency name="SDL.UI.Core.Knockout.ViewModels"/>
                <dependency name="SDL.UI.Core.Knockout.ViewModels.Base"/>
            </dependencies>
        </resourceGroup>

        <resourceGroup name="LVF.ViewModelItems.Product">
            <files>
                <file name="Product.js"/>
            </files>
            <dependencies>
                <dependency name="SDL.UI.Core.Knockout.ViewModels"/>
                <dependency name="SDL.UI.Core.Knockout.ViewModels.Base"/>
            </dependencies>
        </resourceGroup>

        <resourceGroup name="LVF.ViewModelItems.CollectionList">
            <files>
                <file name="CollectionList.js"/>
            </files>
            <dependencies>
                <dependency name="SDL.UI.Core.Knockout.ViewModels"/>
                <dependency name="SDL.UI.Core.Knockout.ViewModels.Base"/>
            </dependencies>
        </resourceGroup>
    </resourceGroups>
</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/UI/Controls/RadioButton/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../SDL.Client.Core/configuration.xsd">

	<resourceGroups>
		<resourceGroup name="SDL.UI.Controls.RadioButton">
			<files>
				<file name="RadioButton.js"/>
				<file name="RadioButton.css"/>
			</files>
			<dependencies>
				<dependency name="SDL.UI.Core.Controls.ControlBase"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.UI.Controls.JQuery.RadioButton">
			<files>
				<file name="RadioButton.jQuery.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Libraries.SDL.JQuery"/>
				<dependency name="SDL.UI.Core.Controls.JQuery"/>
				<dependency name="SDL.UI.Controls.RadioButton"/>
			</dependencies>
		</resourceGroup>
	</resourceGroups>

</configuration>

=== mborysenko/laboratory/projects/catalogue/Leviafan/_Config.xml
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../configuration.xsd">
    <resourceGroups>
        <resourceGroup name="Leviafan.Views.Dashboard">
            <files>
                <file name="dashboard.html"/>
                <file name="dashboard.js"/>
            </files>
            <dependencies>
                <dependency name="SDL.UI.Core.Init"/>
                <dependency name="SDL.UI.Core.Views.ViewBase"/>
            </dependencies>
        </resourceGroup>
    </resourceGroups>
</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/Core/Bootstrap/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../SDL.Client.Core/configuration.xsd">
	<!-- All Libraries -->
	<resourceGroups>

		<resourceGroup name="SDL.Client.Init">
			<files>
				<file name="init.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Application"/>
				<dependency name="SDL.Client.Xml.Base"/>
				<dependency name="SDL.Client.Types.Url2"/>
				<dependency name="SDL.Client.Configuration.ConfigurationManager"/>
				<dependency name="SDL.Client.CrossDomainMessaging"/>
			</dependencies>
		</resourceGroup>

	</resourceGroups>
</configuration>

=== mborysenko/laboratory/projects/architecture/Library/Core/MessageCenter/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../configuration.xsd">

	<!-- Entire MessageCenter Package -->
	<resourceGroups>
		<resourceGroup name="SDL.Client.MessageCenter">
			<files>
				<file name="MessageCenter.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.OO"/>
				<dependency name="SDL.Client.Event.EventRegister"/>
				<dependency name="SDL.Client.Types.ObjectWithEvents"/>
			</dependencies>
		</resourceGroup>
	</resourceGroups>

</configuration>
