=== mborysenko/laboratory/projects/catalogue/Common/Library/Core/configuration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="Schemas/applicationHost.xsd"/>
	<xs:include schemaLocation="Schemas/manifest.xsd"/>
	<xs:include schemaLocation="Schemas/hosting.xsd"/>
	
	<xs:element name="configuration" type="typeConfiguration" />

	<xs:complexType name="typeConfiguration">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:choice>
				<xs:element type="typeAppSettings" name="appSettings" minOccurs="0" maxOccurs="1" />
				<xs:element type="typePages" name="pages" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeInclude" name="include" minOccurs="0" maxOccurs="unbounded" />
				<xs:element type="typeResourceGroups" name="resourceGroups" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeExtensions" name="extensions" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeCustomSections" name="customSections" minOccurs="0" maxOccurs="1" />
				<xs:element type="typePackages" name="packages" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeApplicationHost" name="applicationHost" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeApplicationSuite" name="applicationSuite" minOccurs="0" maxOccurs="1" />
				<xs:element type="typeHosting" name="hosting" minOccurs="0" maxOccurs="1" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="merge" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="generated" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	
	<xs:complexType name="typeAppSettings">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="setting" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typePages">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="page" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="preloadPackages" minOccurs="0">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="package" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="optional" />
											<xs:attribute name="url" type="xs:string" use="required" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="url" type="xs:string" use="required" />
					<xs:attribute name="view" type="xs:string" use="optional" />
					<xs:attribute name="resource" type="xs:string" use="optional" />
					<xs:attribute name="title" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="baseUrl" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="typeResourceGroups">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="resourceGroup">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="files" minOccurs="0">
							<xs:complexType>
								<xs:sequence minOccurs="0">
									<xs:element minOccurs="0" maxOccurs="unbounded" name="file">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required" />
											<xs:attribute name="modification" type="xs:string" use="optional" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" name="dependencies">
							<xs:complexType>
								<xs:sequence minOccurs="0">
									<xs:element maxOccurs="unbounded" name="dependency">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="packaging" type="typeGroupPackaging" use="optional" default="auto"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeInclude">
		<xs:sequence>
			<xs:element name="configuration" type="typeConfiguration" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="src" type="xs:string" use="required" />
		<xs:attribute name="modification" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="typeExtensions">
		<xs:sequence>
			<xs:element name="resourceExtension" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="insert" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="position" type="typeInsertPosition"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="for" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeCustomSections">
		<xs:sequence minOccurs="0">
			<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typePackages">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="package">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="resourceGroups" type="typeResourceGroups" />
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="recursive" type="typePackageRecursive" use="optional" default="auto"/>
					<xs:attribute name="src" type="xs:string" use="optional"/>
					<xs:attribute name="modification" type="xs:string" use="optional" />
					<xs:attribute name="location" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="typeInsertPosition">
		<xs:restriction base="xs:string">
			<xs:enumeration value="before"/>
			<xs:enumeration value="after"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="typeGroupPackaging">
		<xs:restriction base="xs:string">
			<xs:enumeration value="auto"/>
			<xs:enumeration value="exclude"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="typePackageRecursive">
		<xs:annotation>
			<xs:documentation>
				Defines whether dependencies of the specified resource groups should be included too:
				'false' means the dependencies should not be included;
				'auto' (default) means the dependencies should be included, unless another package has them included;
				'true' forces all dependedncies to be included. Use with causion: may result in resources included in multiple groups.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="auto"/>
			<xs:enumeration value="false"/>
			<xs:enumeration value="true"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== mborysenko/laboratory/projects/catalogue/Common/Library/Core/Models/Base/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../configuration.xsd">
	<resourceGroups>
		<resourceGroup name="SDL.Client.Models.Base">
			<files>				
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Base.ContinousIterationObject"/>
				<dependency name="SDL.Client.Models.Base.EditableItem"/>
				<dependency name="SDL.Client.Models.Base.EditableXmlBasedObject"/>
				<dependency name="SDL.Client.Models.Base.FilteredNavigationObject"/>
				<dependency name="SDL.Client.Models.Base.Item"/>
				<dependency name="SDL.Client.Models.Base.List"/>
				<dependency name="SDL.Client.Models.Base.ListFilter"/>
				<dependency name="SDL.Client.Models.Base.ListProvider"/>
				<dependency name="SDL.Client.Models.Base.ModelFactory"/>
				<dependency name="SDL.Client.Models.Base.ObjectWithEditor"/>
				<dependency name="SDL.Client.Models.Base.TreeProvider"/>
				<dependency name="SDL.Client.Models.Base.Tree"/>
				<dependency name="SDL.Client.Models.Base.VersionableItem"/>
				<dependency name="SDL.Client.Models.Base.XmlBasedObject"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Models.Base.ContinousIterationObject">
			<files>
				<file name="ContinuousIterationObject.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>
				<dependency name="SDL.Client.MessageCenter"/>
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Models.Base.EditableItem">
			<files>
				<file name="EditableItem.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>				
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Models.Base.EditableXmlBasedObject">
			<files>
				<file name="EditableXmlBasedObject.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>				
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Models.Base.FilteredNavigationObject">
			<files>
				<file name="FilteredNavigationObject.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>				
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Models.Base.Item">
			<files>
				<file name="Item.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>				
			</dependencies>
		</resourceGroup>
		
		<resourceGroup name="SDL.Client.Models.Base.List">
			<files>
				<file name="List.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>
				<dependency name="SDL.Client.Models.Base.FilteredNavigationObject"/>
			</dependencies>
		</resourceGroup>
		
		<resourceGroup name="SDL.Client.Models.Base.ListFilter">
			<files>
				<file name="ListFilter.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>				
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Models.Base.ListProvider">
			<files>
				<file name="ListProvider.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>				
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Models.Base.Tree">
			<files>
				<file name="Tree.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>
				<dependency name="SDL.Client.MessageCenter"/>
				<dependency name="SDL.Client.Models.Base.FilteredNavigationObject"/>
			</dependencies>
		</resourceGroup>
		
		<resourceGroup name="SDL.Client.Models.Base.ObjectWithEditor">
			<files>
				<file name="ObjectWithEditor.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>
			</dependencies>
		</resourceGroup>
		
		<resourceGroup name="SDL.Client.Models.Base.TreeProvider">
			<files>
				<file name="TreeProvider.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>
				<dependency name="SDL.Client.MessageCenter"/>
			</dependencies>
		</resourceGroup>
		<resourceGroup name="SDL.Client.Models.Base.VersionableItem">
			<files>
				<file name="VersionableItem.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>				
			</dependencies>
		</resourceGroup>
		
		<resourceGroup name="SDL.Client.Models.Base.XmlBasedObject">
			<files>
				<file name="XmlBasedObject.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Models.Classes"/>				
			</dependencies>
		</resourceGroup>

		<resourceGroup name="SDL.Client.Models.Base.ModelFactory">
			<files>
				<file name="ModelFactory.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Types.RegExp"/>
				<dependency name="SDL.Client.Models"/>
			</dependencies>
		</resourceGroup>

	</resourceGroups>


</configuration>

=== mborysenko/laboratory/src/projects/architecture/Library/Core/Libraries/Globalize/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../configuration.xsd">

	<resourceGroups>

		<resourceGroup name="SDL.Client.Libraries.SDL.Globalize">
			<files>
				<file name="SDL.Globalize.js"/>
				<file name="globalize.js"/>
				<file name="SDL.Globalize.init.js"/>
				<file name="cultures/globalize.culture.{CULTURE}.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Libraries.SDL.JQuery"/>
				<dependency name="SDL.Client.Localization"/>
				<dependency name="SDL.Client.Types.Base"/>
				<dependency name="SDL.Client.Types.Date"/>
				<dependency name="SDL.Client.Event.EventRegister"/>
				<dependency name="SDL.Client.Resources.ResourceManager"/>
			</dependencies>
		</resourceGroup>
		
	</resourceGroups>

</configuration>

=== mborysenko/laboratory/projects/architecture/Library/UI/Controls/packages.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../SDL.Client.Core/configuration.xsd">

	<packages>
		<package name="SDL.UI.Controls">
			<resourceGroups>
				<resourceGroup name="SDL.UI.Controls.Tooltip"/>
			</resourceGroups>
		</package>

		<package name="SDL.UI.Controls.JQuery">
			<resourceGroups>
				<resourceGroup name="SDL.UI.Controls.JQuery.Tooltip"/>
			</resourceGroups>
		</package>
	</packages>

</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/Core/pre-configuration.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configuration.xsd">

	<appSettings>
		<setting name="version" value="0.0.0.0" />
	</appSettings>


	<!-- Library core settings -->
	<include src="settings.xml" />

	<!-- Diagnostics resources -->
	<include src="Diagnostics/_Config.xml" />

	<!-- Application resources -->
	<include src="Application/_Config.xml" />

	<!-- ApplicationHost resources -->
	<include src="ApplicationHost/_Config.xml" />

	<!-- Bootstrap resources -->
	<include src="Bootstrap/_Config.xml" />

	<!-- CrossDomainMessaging resources -->
	<include src="CrossDomainMessaging/_Config.xml" />

	<!-- Exception resources -->
	<include src="Exception/_Config.xml" />

	<!-- Repository resources -->
	<include src="Repository/_Config.xml" />

	<!-- Net resources -->
	<include src="Net/_Config.xml" />

	<!-- Resources -->
	<include src="Resources/_Config.xml" />

	<!-- Libraries resources -->
	<include src="Libraries/_Config.xml" />

	<!-- Localization resources -->
	<include src="Localization/_Config.xml" />

	<!-- MessageCenter resources-->
	<include src="MessageCenter/_Config.xml" />

	<!-- Event resources-->
	<include src="Event/_Config.xml" />

	<!-- Types package -->
	<include src="Types/_Config.xml" />

	<!-- Configuration Manager resources -->
	<include src="ConfigurationManager/_Config.xml" />

	<!-- Models resources -->
	<include src="Models/_Config.xml" />

	<!-- Xml resources -->
	<include src="Xml/_Config.xml" />

	<!-- Models configuration -->
	<include src="models.xml" />

	<!-- Packages configuration -->
	<include src="packages.xml" />

	<resourceGroups>
		<resourceGroup name="SDL.Client.Core">
			<files>
				<file name="Bootstrap/registerCorePackage.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Application"/>
				<dependency name="SDL.Client.ApplicationHost"/>
				<dependency name="SDL.Client.Configuration.ConfigurationManager"/>
				<dependency name="SDL.Client.CrossDomainMessaging"/>
				<dependency name="SDL.Client.Diagnostics"/>
				<dependency name="SDL.Client.Event"/>
				<dependency name="SDL.Client.Exception"/>
				<dependency name="SDL.Client.Libraries"/>
				<dependency name="SDL.Client.Localization"/>
				<dependency name="SDL.Client.MessageCenter"/>
				<dependency name="SDL.Client.Net"/>
				<dependency name="SDL.Client.Resources"/>
				<dependency name="SDL.Client.Types"/>
				<dependency name="SDL.Client.Xml"/>
				<dependency name="SDL.Client.Resources.ResourceManager"/>
			</dependencies>
		</resourceGroup>
	</resourceGroups>

</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/UI/Controls.Knockout/LineGraph/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../SDL.Client.Core/configuration.xsd">

	<resourceGroups>
		<resourceGroup name="SDL.UI.Controls.Knockout.LineGraph">
			<files>
				<file name="LineGraph.css"/>
				<file name="app.js"/>
				<file name="LineGraphKo.js"/>
				<file name="LineGraph.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Libraries.SDL.Globalize" />
				<dependency name="SDL.UI.Core.Knockout.Libraries.Knockout"/>
				<dependency name="SDL.UI.Libraries.D3"/>
			</dependencies>
		</resourceGroup>
	</resourceGroups>
</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/Core/ApplicationHost/_Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../configuration.xsd">
	<resourceGroups>
		<resourceGroup name="SDL.Client.ApplicationHost">
			<files>
				<file name="ApplicationManifestReceiver.js"/>
				<file name="ApplicationHost.js"/>
				<file name="ApplicationHostFacade.js"/>
			</files>
			<dependencies>
				<dependency name="SDL.Client.Xml"/>
				<dependency name="SDL.Client.Types.Object"/>
				<dependency name="SDL.Client.Types.Array"/>
				<dependency name="SDL.Client.Types.Url"/>
				<dependency name="SDL.Client.Configuration.ConfigurationManager"/>
				<dependency name="SDL.Client.CrossDomainMessaging"/>
				<dependency name="SDL.Client.Resources.ResourceManager"/>
			</dependencies>
		</resourceGroup>
	</resourceGroups>
</configuration>

=== mborysenko/laboratory/projects/catalogue/Common/Library/UI/Controls.Knockout/packages.xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../SDL.Client.Core/configuration.xsd">

	<packages>
		<package name="SDL.UI.Controls.Knockout">
			<resourceGroups>
				<resourceGroup name="SDL.UI.Controls.Knockout.ActionBar"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.ActivityIndicator"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.Button"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.Callout"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.Dialog"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.Message"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.ResizeTrigger"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.TopBar"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.TopPageTabs"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.Tooltip"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.ScrollView"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.LineGraph"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.TextInput"/>
                <resourceGroup name="SDL.UI.Controls.Knockout.DatePicker"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.Checkbox"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.RadioButton"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.DropdownList"/>
				<resourceGroup name="SDL.UI.Controls.Knockout.Application.ViewModels.TopBar"/>
			</resourceGroups>
		</package>
	</packages>

</configuration>

=== mborysenko/laboratory/projects/catalogue/Leviafan/Controls/_config.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../../Common/Library/Core/configuration.xsd">
    <resourceGroups>

        <resourceGroup name="LVF.Controls.Navigation">
            <files>
                <file name="Navigation/Navigation.js"/>
            </files>
            <dependencies>
                <dependency name="SDL.UI.Core.Knockout.Controls"/>
            </dependencies>
        </resourceGroup>

        <resourceGroup name="LVF.Controls.Knockout.Navigation">
            <files>
                <file name="Knockout/Navigation.js"/>
            </files>
            <dependencies>
                <dependency name="LVF.Controls.Navigation"/>
            </dependencies>
        </resourceGroup>

    </resourceGroups>
</configuration>
